spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_vitor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vitor52639401

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
